[workspace.package]
version = "0.1.0-alpha.5"
authors = ["Stürmer, Benjamin <benjamin@stuermer.pro>"]
repository = "https://github.com/zigbee-rs"
readme = "README.md"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace]
members = [
    "zigbee",
    "zigbee-core",
    "zigbee-base-device-behavior",
    "zigbee-cluster-library",
    "zigbee-macros",
    "zigbee-types",
]
exclude = [
	"zigbee-mac"
]
resolver = "3"

[workspace.dependencies]
zigbee-core = { version = "0.1.0-alpha.5", path = "zigbee-core" }
zigbee-types = { version = "0.1.0-alpha.5", path = "zigbee-types" }
zigbee-macros = { version = "0.1.0-alpha.5", path = "zigbee-macros" }
zigbee-mac = { version = "0.1.0-alpha.5", path = "zigbee-mac" }
zigbee-cluster-library = { version = "0.1.0-alpha.5", path = "zigbee-cluster-library" }
zigbee-base-device-behavior = { version = "0.1.0-alpha.5", path = "zigbee-base-device-behavior" }

aes = "0.8.4"
atomic-waker = "1.1"
embedded-hal-async = "1.0"
byte = "0.2.7"
ccm = { version = "0.5.0", default-features = false }
aead = { version = "0.5.0", default-features = false }
itertools = { version = "0.14.0", default-features = false }
embedded-storage = "0.3.1"
embedded-storage-async = "0.4.1"
sequential-storage = "7.2.0"
heapless = "0.9.1"
log = "0.4"
mockall = "0.13"
spin = { version = "0.10.0", default-features = false, features = ["spin_mutex", "mutex", "rwlock"] }
thiserror = { version = "2.0.6", default-features = false }
