[package]
name = "zigbee-base-device-behavior"
version.workspace = true

description = "Zigbee base device behavior based on the official Zigbee Base Device Behavior Specification Rev 13"
documentation = "https://docs.rs/zigbee-base-device-behavior"
readme = "README.md"
keywords = ["zigbee", "ieee802154", "base-device-behavior", "bdb"]
categories = ["network-programming", "no-std", "embedded"]
license = "MIT OR Apache-2.0"

authors.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
embedded-hal-async.workspace = true
spin.workspace = true
thiserror.workspace = true
log.workspace = true
zigbee-core.workspace = true
zigbee-mac.workspace = true
zigbee-types.workspace = true

[dev-dependencies]
mockall.workspace = true
zigbee-types.workspace = true

[package.metadata.docs.rs]
all-features = true
