[package]
name = "zigbee-cluster-library"
version.workspace = true

description = "Zigbee cluster library in `no-std` based on the official Zigbee Cluster Library Specification Rev 8"
documentation = "https://docs.rs/zigbee-cluster-library"
readme = "README.md"
keywords = ["zigbee", "ieee802154", "cluster-library", "zcl"]
categories = ["network-programming", "no-std", "embedded"]
license = "MIT OR Apache-2.0"

authors.workspace = true
edition = "2024"

[features]

[dependencies]
byte.workspace = true
embedded-hal-async.workspace = true
heapless.workspace = true

zigbee-core.workspace = true
zigbee-mac.workspace = true
zigbee-macros.workspace = true

[package.metadata.docs.rs]
all-features = true
