//! ZCL compliance harness
//!
//! Run: `cargo test --test zcl_compliance`
//!
//! The harness loads byte fixtures from `vectors/zcl_data_types.json`.
//! Fixtures are generated by `scripts/gen_vectors.py` using zigpy as the
//! reference implementation. Normal Rust tests do not require Python or zigpy.
//!
//! ## Fixture conventions
//!
//! | Field            | Used by                                      |
//! |------------------|----------------------------------------------|
//! | `roundtrip`      | scalars, enums, strings, collections, struct |
//! | `roundtrip_bits` | f32, f64 (NaN-safe bit repr)                 |
//! | `roundtrip_raw`  | bitmaps (raw primitive repr)                 |
//! | `null_wire`      | all nullable types                           |
//! | `type_mismatch`  | typed collections                            |
//! | `invalid`        | malformed collection and struct wires        |
//! | `valid`          | set collections                              |
//! | `duplicate`      | set collections                              |
//! | `invalid_value`  | bool invalid non-null values                 |
//! | `invalid_utf8`   | short_text                                   |

use std::collections::BTreeMap;
use std::sync::LazyLock;

use serde::Deserialize;
use serde::de::DeserializeOwned;
use serde_json::Value;
use zigbee_cluster_library::types::Array;
use zigbee_cluster_library::types::ArrayOf;
use zigbee_cluster_library::types::ArrayRef;
use zigbee_cluster_library::types::Bag;
use zigbee_cluster_library::types::BagOf;
use zigbee_cluster_library::types::Bitmap8;
use zigbee_cluster_library::types::Bitmap16;
use zigbee_cluster_library::types::Bitmap32;
use zigbee_cluster_library::types::Bitmap64;
use zigbee_cluster_library::types::CollectionEncoder;
use zigbee_cluster_library::types::Enum8;
use zigbee_cluster_library::types::Enum16;
use zigbee_cluster_library::types::Nullable;
use zigbee_cluster_library::types::RawUniqueSet;
use zigbee_cluster_library::types::Set;
use zigbee_cluster_library::types::SetOf;
use zigbee_cluster_library::types::ShortOctetString;
use zigbee_cluster_library::types::ShortStr;
use zigbee_cluster_library::types::ShortText;
use zigbee_cluster_library::types::StructDecoder;
use zigbee_cluster_library::types::StructEncoder;
use zigbee_cluster_library::types::StructOf;
use zigbee_cluster_library::types::TypeId;
use zigbee_cluster_library::types::ZclBitmap8;
use zigbee_cluster_library::types::ZclBitmap16;
use zigbee_cluster_library::types::ZclBitmap32;
use zigbee_cluster_library::types::ZclBitmap64;
use zigbee_cluster_library::types::ZclEnum8;
use zigbee_cluster_library::types::ZclEnum16;
use zigbee_cluster_library::types::ZclError;
use zigbee_cluster_library::types::ZclHasNull;
use zigbee_cluster_library::types::ZclSchema;
use zigbee_cluster_library::types::ZclStructSchema;
use zigbee_cluster_library::types::ZclValueRef;

#[derive(Debug, Deserialize)]
struct FixtureFile {
    schema_version: u32,
    source: FixtureSource,
    types: BTreeMap<String, TypeFixture>,
}

#[derive(Debug, Deserialize)]
struct FixtureSource {
    generator: String,
    zigpy: String,
}

#[derive(Debug, Deserialize)]
struct TypeFixture {
    type_id: u8,
    #[serde(default)]
    roundtrip: Vec<Case>,
    #[serde(default)]
    roundtrip_bits: Vec<Case>,
    #[serde(default)]
    roundtrip_raw: Vec<Case>,
    #[serde(default)]
    null_wire: Vec<WireCase>,
    #[serde(default)]
    type_mismatch: Vec<TypeMismatchCase>,
    #[serde(default)]
    invalid: Vec<InvalidCase>,
    #[serde(default)]
    valid: Vec<Case>,
    #[serde(default)]
    duplicate: Vec<WireCase>,
    #[serde(default)]
    invalid_value: Vec<WireCase>,
    #[serde(default)]
    invalid_utf8: Vec<WireCase>,
}

#[derive(Debug, Deserialize)]
struct WireCase {
    name: String,
    wire: String,
}

#[derive(Debug, Deserialize)]
struct TypeMismatchCase {
    name: String,
    wire: String,
    expected: u8,
    found: u8,
}

#[derive(Debug, Deserialize)]
struct InvalidCase {
    name: String,
    wire: String,
    error: String,
    #[serde(default)]
    expected: Option<u8>,
    #[serde(default)]
    found: Option<u8>,
}

#[derive(Debug, Deserialize)]
struct Case {
    name: String,
    wire: String,
    #[serde(default)]
    value: Value,
    #[serde(default)]
    values: Vec<Value>,
    #[serde(default)]
    value_hex: Option<String>,
    #[serde(default)]
    bits: Option<u64>,
    #[serde(default)]
    inner_wires: Vec<String>,
}

static FIXTURES: LazyLock<FixtureFile> = LazyLock::new(|| {
    let parsed: FixtureFile = serde_json::from_str(include_str!("vectors/zcl_data_types.json"))
        .expect("zcl_data_types.json fixture should parse");
    assert_eq!(parsed.schema_version, 1, "fixture schema version changed");
    assert_eq!(parsed.source.generator, "scripts/gen_vectors.py");
    assert!(!parsed.source.zigpy.is_empty(), "zigpy version missing");
    parsed
});

fn fixture(name: &str) -> &'static TypeFixture {
    FIXTURES
        .types
        .get(name)
        .unwrap_or_else(|| panic!("fixture {name:?} missing"))
}

fn parse_wire(encoded: &str) -> Vec<u8> {
    let compact = encoded.split_whitespace().collect::<String>();
    assert_eq!(compact.len() % 2, 0, "odd-length hex wire: {encoded}");
    (0..compact.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&compact[i..i + 2], 16).expect("fixture hex byte"))
        .collect()
}

fn wire_case(case: &WireCase) -> Vec<u8> {
    parse_wire(&case.wire)
}

fn type_mismatch_wire(case: &TypeMismatchCase) -> Vec<u8> {
    parse_wire(&case.wire)
}

fn invalid_wire(case: &InvalidCase) -> Vec<u8> {
    parse_wire(&case.wire)
}

fn case_wire(case: &Case) -> Vec<u8> {
    parse_wire(&case.wire)
}

fn type_id(raw: u8) -> TypeId {
    TypeId::from_u8(raw)
}

fn dynamic_roundtrip_cases(fixture: &TypeFixture) -> impl Iterator<Item = &Case> {
    fixture
        .roundtrip
        .iter()
        .chain(&fixture.roundtrip_bits)
        .chain(&fixture.roundtrip_raw)
        .chain(&fixture.valid)
}

fn dynamic_null_supported(type_id: TypeId) -> bool {
    matches!(
        type_id,
        TypeId::CharacterString
            | TypeId::OctetString
            | TypeId::Array
            | TypeId::Set
            | TypeId::Bag
            | TypeId::Structure
    )
}

fn assert_dynamic_value_roundtrip(type_id: TypeId, wire: &[u8], context: &str) {
    let (value, n) = ZclValueRef::decode_with_type(type_id, wire)
        .unwrap_or_else(|e| panic!("{context} dynamic decode → {e:?}"));
    assert_eq!(n, wire.len(), "{context} dynamic decode consumed");
    assert_eq!(value.type_id(), type_id, "{context} dynamic type id");
    assert_eq!(value.encoded_len(), wire.len(), "{context} encoded len");

    let mut buf = vec![0u8; wire.len()];
    let written = value
        .encode(&mut buf)
        .unwrap_or_else(|e| panic!("{context} dynamic encode → {e:?}"));
    assert_eq!(written, wire.len(), "{context} dynamic encode len");
    assert_eq!(buf.as_slice(), wire, "{context} dynamic encode wire");
}

fn assert_type_mismatch(actual: ZclError, expected: u8, found: u8, context: &str) {
    assert_eq!(
        actual,
        ZclError::TypeIdMismatch {
            expected: type_id(expected),
            found: type_id(found),
        },
        "{context}",
    );
}

fn assert_zcl_error(actual: ZclError, case: &InvalidCase, context: &str) {
    match case.error.as_str() {
        "InsufficientBytes" => assert_eq!(actual, ZclError::InsufficientBytes, "{context}"),
        "InvalidLength" => assert_eq!(actual, ZclError::InvalidLength, "{context}"),
        "InvalidValue" => assert_eq!(actual, ZclError::InvalidValue, "{context}"),
        "InvalidUtf8" => assert_eq!(actual, ZclError::InvalidUtf8, "{context}"),
        "NullSentinel" => assert_eq!(actual, ZclError::NullSentinel, "{context}"),
        "UnconsumedData" => assert_eq!(actual, ZclError::UnconsumedData, "{context}"),
        "TypeIdMismatch" => assert_type_mismatch(
            actual,
            case.expected
                .unwrap_or_else(|| panic!("{context}: missing expected type id")),
            case.found
                .unwrap_or_else(|| panic!("{context}: missing found type id")),
            context,
        ),
        other => panic!("{context}: unknown expected error {other}"),
    }
}

fn assert_type_mismatch_case(actual: ZclError, case: &TypeMismatchCase, context: &str) {
    assert_type_mismatch(actual, case.expected, case.found, context);
}

fn case_value<T: DeserializeOwned>(case: &Case) -> T {
    serde_json::from_value(case.value.clone())
        .unwrap_or_else(|e| panic!("{} value does not match expected type: {e}", case.name))
}

fn case_values<T: DeserializeOwned>(case: &Case) -> Vec<T> {
    case.values
        .iter()
        .cloned()
        .map(|value| {
            serde_json::from_value(value).unwrap_or_else(|e| {
                panic!("{} element does not match expected type: {e}", case.name)
            })
        })
        .collect()
}

fn case_bytes(case: &Case) -> Vec<u8> {
    parse_wire(
        case.value_hex
            .as_deref()
            .unwrap_or_else(|| panic!("{} missing value_hex", case.name)),
    )
}

fn case_bits_u32(case: &Case) -> u32 {
    case.bits
        .unwrap_or_else(|| panic!("{} missing bits", case.name))
        .try_into()
        .unwrap_or_else(|_| panic!("{} bits do not fit u32", case.name))
}

fn case_bits_u64(case: &Case) -> u64 {
    case.bits
        .unwrap_or_else(|| panic!("{} missing bits", case.name))
}

fn value_pair(value: &Value) -> (u8, u16) {
    let pair = value.as_array().expect("pair value should be array");
    assert_eq!(pair.len(), 2, "pair should have two fields");
    let first = serde_json::from_value(pair[0].clone()).expect("pair u8");
    let second = serde_json::from_value(pair[1].clone()).expect("pair u16");
    (first, second)
}

fn case_pair(case: &Case) -> (u8, u16) {
    value_pair(&case.value)
}

fn case_pairs(case: &Case) -> Vec<(u8, u16)> {
    case.values.iter().map(value_pair).collect()
}

fn case_struct_with_array(case: &Case) -> (u8, Vec<u8>) {
    let object = case
        .value
        .as_object()
        .expect("struct value should be object");
    let u8_value = serde_json::from_value(object["u8"].clone()).expect("struct u8 field");
    let array = serde_json::from_value(object["array"].clone()).expect("struct array field");
    (u8_value, array)
}

fn decode_err<S: ZclSchema>(wire: &[u8], context: &str) -> ZclError {
    match S::decode(wire) {
        Ok(_) => panic!("{context}: decode unexpectedly succeeded"),
        Err(err) => err,
    }
}

fn nullable_decode_err<S: ZclHasNull>(wire: &[u8], context: &str) -> ZclError {
    match Nullable::<S>::decode(wire) {
        Ok(_) => panic!("{context}: Nullable decode unexpectedly succeeded"),
        Err(err) => err,
    }
}

fn assert_null_wire_rejected<S: ZclSchema>(fixture_name: &str) {
    let fixture = fixture(fixture_name);
    for case in &fixture.null_wire {
        let wire = wire_case(case);
        assert_eq!(
            decode_err::<S>(&wire, &format!("{fixture_name}/{}", case.name)),
            ZclError::NullSentinel,
            "{fixture_name}/{}",
            case.name,
        );
    }
}

fn assert_nullable_none_decode<S: ZclHasNull>(fixture_name: &str) {
    let fixture = fixture(fixture_name);
    for case in &fixture.null_wire {
        let wire = wire_case(case);
        let (val, n) = Nullable::<S>::decode(&wire)
            .unwrap_or_else(|e| panic!("{fixture_name}/{} Nullable decode → {e:?}", case.name));
        assert!(val.is_none(), "{fixture_name}/{}", case.name);
        assert_eq!(n, wire.len(), "{fixture_name}/{}", case.name);
    }
}

fn assert_nullable_none_encode<S: ZclHasNull>(fixture_name: &str, buf: &mut [u8]) {
    let fixture = fixture(fixture_name);
    for case in &fixture.null_wire {
        let wire = wire_case(case);
        let n = Nullable::<S>::encode(None, buf).unwrap_or_else(|e| {
            panic!("{fixture_name}/{} Nullable encode None → {e:?}", case.name)
        });
        assert_eq!(&buf[..n], wire.as_slice(), "{fixture_name}/{}", case.name);
    }
}

fn assert_type_mismatch_rejected<S: ZclSchema>(fixture_name: &str) {
    let fixture = fixture(fixture_name);
    for case in &fixture.type_mismatch {
        let wire = type_mismatch_wire(case);
        assert_type_mismatch_case(
            decode_err::<S>(&wire, &format!("{fixture_name}/{}", case.name)),
            case,
            &format!("{fixture_name}/{}", case.name),
        );
    }
}

fn assert_invalid_wire_errors_match_fixture<S: ZclSchema>(fixture_name: &str) {
    let fixture = fixture(fixture_name);
    for case in &fixture.invalid {
        let wire = invalid_wire(case);
        let context = format!("{fixture_name}/{}", case.name);
        assert_zcl_error(
            decode_err::<S>(&wire, &format!("{fixture_name}/{}", case.name)),
            case,
            &context,
        );
    }
}

fn assert_invalid_nullable_errors_match_fixture<S: ZclHasNull>(fixture_name: &str) {
    let fixture = fixture(fixture_name);
    for case in &fixture.invalid {
        let wire = invalid_wire(case);
        let context = format!("{fixture_name}/{} nullable", case.name);
        assert_zcl_error(nullable_decode_err::<S>(&wire, &context), case, &context);
    }
}

// ---------------------------------------------------------------------------
// Test-only passthrough helpers for parametric schemas
// ---------------------------------------------------------------------------

#[derive(Clone, Copy, PartialEq, Debug)]
struct RawBitmap8(u8);
impl ZclBitmap8 for RawBitmap8 {
    fn from_bits(b: u8) -> Self {
        Self(b)
    }
    fn into_bits(self) -> u8 {
        self.0
    }
}

#[derive(Clone, Copy, PartialEq, Debug)]
struct RawBitmap16(u16);
impl ZclBitmap16 for RawBitmap16 {
    fn from_bits(b: u16) -> Self {
        Self(b)
    }
    fn into_bits(self) -> u16 {
        self.0
    }
}

#[derive(Clone, Copy, PartialEq, Debug)]
struct RawBitmap32(u32);
impl ZclBitmap32 for RawBitmap32 {
    fn from_bits(b: u32) -> Self {
        Self(b)
    }
    fn into_bits(self) -> u32 {
        self.0
    }
}

#[derive(Clone, Copy, PartialEq, Debug)]
struct RawBitmap64(u64);
impl ZclBitmap64 for RawBitmap64 {
    fn from_bits(b: u64) -> Self {
        Self(b)
    }
    fn into_bits(self) -> u64 {
        self.0
    }
}

#[derive(Clone, Copy, PartialEq, Debug)]
struct RawEnum8(u8);
impl ZclEnum8 for RawEnum8 {
    fn from_raw(raw: u8) -> Result<Self, ZclError> {
        Ok(Self(raw))
    }
    fn into_raw(self) -> u8 {
        self.0
    }
}

#[derive(Clone, Copy, PartialEq, Debug)]
struct RawEnum16(u16);
impl ZclEnum16 for RawEnum16 {
    fn from_raw(raw: u16) -> Result<Self, ZclError> {
        Ok(Self(raw))
    }
    fn into_raw(self) -> u16 {
        self.0
    }
}

// ---------------------------------------------------------------------------
// Scalar macro — ROUNDTRIP + NULL_WIRE + Nullable<T>
// ---------------------------------------------------------------------------

macro_rules! scalar_compliance {
    ($mod_name:ident, $schema:ty, $fixture:literal) => {
        mod $mod_name {
            use super::*;

            #[test]
            fn decode_roundtrip() {
                let fixture = fixture($fixture);
                for case in &fixture.roundtrip {
                    let wire = case_wire(case);
                    let expected: $schema = case_value(case);
                    let (val, n) = <$schema>::decode(&wire).unwrap_or_else(|e| {
                        panic!("{}/{} decode {:?} → {e:?}", $fixture, case.name, wire)
                    });
                    assert_eq!(val, expected, "{}/{}", $fixture, case.name);
                    assert_eq!(
                        n,
                        wire.len(),
                        "{}/{} consumed {n} of {}",
                        $fixture,
                        case.name,
                        wire.len()
                    );
                }
            }

            #[test]
            fn encode_roundtrip() {
                let fixture = fixture($fixture);
                let mut buf = [0u8; 32];
                for case in &fixture.roundtrip {
                    let wire = case_wire(case);
                    let expected: $schema = case_value(case);
                    let n = <$schema>::encode(expected, &mut buf).unwrap_or_else(|e| {
                        panic!("{}/{} encode {expected:?} → {e:?}", $fixture, case.name)
                    });
                    assert_eq!(&buf[..n], wire.as_slice(), "{}/{}", $fixture, case.name);
                }
            }

            #[test]
            fn null_wire_rejected() {
                let fixture = fixture($fixture);
                for case in &fixture.null_wire {
                    let wire = wire_case(case);
                    assert_eq!(
                        <$schema>::decode(&wire).unwrap_err(),
                        ZclError::NullSentinel,
                        "{}/{}",
                        $fixture,
                        case.name,
                    );
                }
            }

            #[test]
            fn nullable_none_decode() {
                let fixture = fixture($fixture);
                for case in &fixture.null_wire {
                    let wire = wire_case(case);
                    let (val, n) = Nullable::<$schema>::decode(&wire).unwrap_or_else(|e| {
                        panic!(
                            "{}/{} Nullable decode {:?} → {e:?}",
                            $fixture, case.name, wire
                        )
                    });
                    assert!(val.is_none(), "{}/{}", $fixture, case.name);
                    assert_eq!(n, wire.len(), "{}/{}", $fixture, case.name);
                }
            }

            #[test]
            fn nullable_none_encode() {
                let fixture = fixture($fixture);
                let mut buf = [0u8; 32];
                for case in &fixture.null_wire {
                    let wire = wire_case(case);
                    let n = Nullable::<$schema>::encode(None, &mut buf).unwrap_or_else(|e| {
                        panic!("{}/{} Nullable encode None → {e:?}", $fixture, case.name)
                    });
                    assert_eq!(&buf[..n], wire.as_slice(), "{}/{}", $fixture, case.name);
                }
            }
        }
    };
}

scalar_compliance!(u8_compliance, u8, "u8");
scalar_compliance!(u16_compliance, u16, "u16");
scalar_compliance!(u32_compliance, u32, "u32");
scalar_compliance!(u64_compliance, u64, "u64");
scalar_compliance!(i8_compliance, i8, "i8");
scalar_compliance!(i16_compliance, i16, "i16");
scalar_compliance!(i32_compliance, i32, "i32");
scalar_compliance!(i64_compliance, i64, "i64");

// ---------------------------------------------------------------------------
// ShortOctetString — byte-slice value needs dedicated fixture extraction
// ---------------------------------------------------------------------------

mod short_octet_string_compliance {
    use super::*;

    #[test]
    fn decode_roundtrip() {
        let fixture = fixture("short_octet_string");
        for case in &fixture.roundtrip {
            let wire = case_wire(case);
            let expected = case_bytes(case);
            let (val, n) = ShortOctetString::decode(&wire)
                .unwrap_or_else(|e| panic!("short_octet_string/{} decode → {e:?}", case.name));
            assert_eq!(val, expected.as_slice(), "short_octet_string/{}", case.name);
            assert_eq!(n, wire.len());
        }
    }

    #[test]
    fn encode_roundtrip() {
        let fixture = fixture("short_octet_string");
        let mut buf = [0u8; 32];
        for case in &fixture.roundtrip {
            let wire = case_wire(case);
            let expected = case_bytes(case);
            let n = ShortOctetString::encode(expected.as_slice(), &mut buf)
                .unwrap_or_else(|e| panic!("short_octet_string/{} encode → {e:?}", case.name));
            assert_eq!(
                &buf[..n],
                wire.as_slice(),
                "short_octet_string/{}",
                case.name
            );
        }
    }

    #[test]
    fn null_wire_rejected() {
        let fixture = fixture("short_octet_string");
        for case in &fixture.null_wire {
            let wire = wire_case(case);
            assert_eq!(
                ShortOctetString::decode(&wire).unwrap_err(),
                ZclError::NullSentinel
            );
        }
    }

    #[test]
    fn nullable_none_decode() {
        let fixture = fixture("short_octet_string");
        for case in &fixture.null_wire {
            let wire = wire_case(case);
            let (val, n) = Nullable::<ShortOctetString>::decode(&wire).unwrap();
            assert!(val.is_none());
            assert_eq!(n, wire.len());
        }
    }

    #[test]
    fn nullable_none_encode() {
        let fixture = fixture("short_octet_string");
        let mut buf = [0u8; 1];
        for case in &fixture.null_wire {
            let wire = wire_case(case);
            let n = Nullable::<ShortOctetString>::encode(None, &mut buf).unwrap();
            assert_eq!(&buf[..n], wire.as_slice());
        }
    }
}

// ---------------------------------------------------------------------------
// Float macro — ROUNDTRIP_BITS (bit-exact, NaN-safe) + NULL_WIRE
// ---------------------------------------------------------------------------

macro_rules! float_compliance {
    ($mod_name:ident, $schema:ty, $bits:ident, $fixture:literal) => {
        mod $mod_name {
            use super::*;

            #[test]
            fn decode_roundtrip() {
                let fixture = fixture($fixture);
                for case in &fixture.roundtrip_bits {
                    let wire = case_wire(case);
                    let expected_bits = $bits(case);
                    let (val, n) = <$schema>::decode(&wire).unwrap_or_else(|e| {
                        panic!("{}/{} decode {:?} → {e:?}", $fixture, case.name, wire)
                    });
                    assert_eq!(val.to_bits(), expected_bits, "{}/{}", $fixture, case.name);
                    assert_eq!(n, wire.len());
                }
            }

            #[test]
            fn encode_roundtrip() {
                let fixture = fixture($fixture);
                let mut buf = [0u8; 16];
                for case in &fixture.roundtrip_bits {
                    let wire = case_wire(case);
                    let expected_bits = $bits(case);
                    let val = <$schema>::from_bits(expected_bits);
                    let n = <$schema>::encode(val, &mut buf).unwrap_or_else(|e| {
                        panic!(
                            "{}/{} encode bits={expected_bits} → {e:?}",
                            $fixture, case.name
                        )
                    });
                    assert_eq!(&buf[..n], wire.as_slice(), "{}/{}", $fixture, case.name);
                }
            }

            #[test]
            fn null_wire_rejected() {
                let fixture = fixture($fixture);
                for case in &fixture.null_wire {
                    let wire = wire_case(case);
                    assert_eq!(
                        <$schema>::decode(&wire).unwrap_err(),
                        ZclError::NullSentinel,
                        "{}/{}",
                        $fixture,
                        case.name,
                    );
                }
            }

            #[test]
            fn nullable_none_decode() {
                let fixture = fixture($fixture);
                for case in &fixture.null_wire {
                    let wire = wire_case(case);
                    let (val, n) = Nullable::<$schema>::decode(&wire).unwrap();
                    assert!(val.is_none());
                    assert_eq!(n, wire.len());
                }
            }

            #[test]
            fn nullable_none_encode() {
                let fixture = fixture($fixture);
                let mut buf = [0u8; 16];
                for case in &fixture.null_wire {
                    let wire = wire_case(case);
                    let n = Nullable::<$schema>::encode(None, &mut buf).unwrap();
                    assert_eq!(&buf[..n], wire.as_slice());
                }
            }
        }
    };
}

float_compliance!(f32_compliance, f32, case_bits_u32, "f32");
float_compliance!(f64_compliance, f64, case_bits_u64, "f64");

// ---------------------------------------------------------------------------
// Bitmap macro — ROUNDTRIP_RAW, no null sentinel (all bit patterns valid)
// ---------------------------------------------------------------------------

macro_rules! bitmap_compliance {
    ($mod_name:ident, $schema:ty, $raw_type:ty, $raw_value:ty, $fixture:literal) => {
        mod $mod_name {
            use super::*;

            #[test]
            fn decode_roundtrip() {
                let fixture = fixture($fixture);
                for case in &fixture.roundtrip_raw {
                    let wire = case_wire(case);
                    let expected_raw: $raw_value = case_value(case);
                    let (val, n) = <$schema>::decode(&wire).unwrap_or_else(|e| {
                        panic!("{}/{} decode {:?} → {e:?}", $fixture, case.name, wire)
                    });
                    assert_eq!(val.into_bits(), expected_raw, "{}/{}", $fixture, case.name);
                    assert_eq!(n, wire.len());
                }
            }

            #[test]
            fn encode_roundtrip() {
                let fixture = fixture($fixture);
                let mut buf = [0u8; 16];
                for case in &fixture.roundtrip_raw {
                    let wire = case_wire(case);
                    let expected_raw: $raw_value = case_value(case);
                    let val = <$raw_type>::from_bits(expected_raw);
                    let n = <$schema>::encode(val, &mut buf).unwrap_or_else(|e| {
                        panic!(
                            "{}/{} encode raw={expected_raw} → {e:?}",
                            $fixture, case.name
                        )
                    });
                    assert_eq!(&buf[..n], wire.as_slice(), "{}/{}", $fixture, case.name);
                }
            }
        }
    };
}

bitmap_compliance!(
    bitmap8_compliance,
    Bitmap8<RawBitmap8>,
    RawBitmap8,
    u8,
    "bitmap8"
);
bitmap_compliance!(
    bitmap16_compliance,
    Bitmap16<RawBitmap16>,
    RawBitmap16,
    u16,
    "bitmap16"
);
bitmap_compliance!(
    bitmap32_compliance,
    Bitmap32<RawBitmap32>,
    RawBitmap32,
    u32,
    "bitmap32"
);
bitmap_compliance!(
    bitmap64_compliance,
    Bitmap64<RawBitmap64>,
    RawBitmap64,
    u64,
    "bitmap64"
);

// ---------------------------------------------------------------------------
// Enum macro — ROUNDTRIP (raw discriminant) + NULL_WIRE
// ---------------------------------------------------------------------------

macro_rules! enum_compliance {
    ($mod_name:ident, $schema:ty, $raw_helper:ident, $raw_value:ty, $buf_size:expr, $fixture:literal) => {
        mod $mod_name {
            use super::*;

            #[test]
            fn decode_roundtrip() {
                let fixture = fixture($fixture);
                for case in &fixture.roundtrip {
                    let wire = case_wire(case);
                    let expected_raw: $raw_value = case_value(case);
                    let (val, n) = <$schema>::decode(&wire).unwrap_or_else(|e| {
                        panic!("{}/{} decode {:?} → {e:?}", $fixture, case.name, wire)
                    });
                    assert_eq!(val, $raw_helper(expected_raw), "{}/{}", $fixture, case.name);
                    assert_eq!(n, wire.len());
                }
            }

            #[test]
            fn encode_roundtrip() {
                let fixture = fixture($fixture);
                let mut buf = [0u8; $buf_size];
                for case in &fixture.roundtrip {
                    let wire = case_wire(case);
                    let expected_raw: $raw_value = case_value(case);
                    let n = <$schema>::encode($raw_helper(expected_raw), &mut buf).unwrap_or_else(
                        |e| {
                            panic!(
                                "{}/{} encode raw={expected_raw} → {e:?}",
                                $fixture, case.name
                            )
                        },
                    );
                    assert_eq!(&buf[..n], wire.as_slice(), "{}/{}", $fixture, case.name);
                }
            }

            #[test]
            fn null_wire_rejected() {
                let fixture = fixture($fixture);
                for case in &fixture.null_wire {
                    let wire = wire_case(case);
                    assert_eq!(
                        <$schema>::decode(&wire).unwrap_err(),
                        ZclError::NullSentinel,
                        "{}/{}",
                        $fixture,
                        case.name,
                    );
                }
            }

            #[test]
            fn nullable_none_decode() {
                let fixture = fixture($fixture);
                for case in &fixture.null_wire {
                    let wire = wire_case(case);
                    let (val, n) = Nullable::<$schema>::decode(&wire).unwrap();
                    assert!(val.is_none());
                    assert_eq!(n, wire.len());
                }
            }

            #[test]
            fn nullable_none_encode() {
                let fixture = fixture($fixture);
                let mut buf = [0u8; $buf_size];
                for case in &fixture.null_wire {
                    let wire = wire_case(case);
                    let n = Nullable::<$schema>::encode(None, &mut buf).unwrap();
                    assert_eq!(&buf[..n], wire.as_slice());
                }
            }
        }
    };
}

enum_compliance!(enum8_compliance, Enum8<RawEnum8>, RawEnum8, u8, 4, "enum8");
enum_compliance!(
    enum16_compliance,
    Enum16<RawEnum16>,
    RawEnum16,
    u16,
    4,
    "enum16"
);

// ---------------------------------------------------------------------------
// Bool — ROUNDTRIP + NULL_WIRE + INVALID_VALUE
// ---------------------------------------------------------------------------

mod bool_compliance {
    use super::*;

    #[test]
    fn decode_roundtrip() {
        let fixture = fixture("bool");
        for case in &fixture.roundtrip {
            let wire = case_wire(case);
            let expected: bool = case_value(case);
            let (val, n) =
                bool::decode(&wire).unwrap_or_else(|e| panic!("bool/{} decode → {e:?}", case.name));
            assert_eq!(val, expected, "bool/{}", case.name);
            assert_eq!(n, wire.len());
        }
    }

    #[test]
    fn encode_roundtrip() {
        let fixture = fixture("bool");
        let mut buf = [0u8; 1];
        for case in &fixture.roundtrip {
            let wire = case_wire(case);
            let expected: bool = case_value(case);
            let n = bool::encode(expected, &mut buf).unwrap();
            assert_eq!(&buf[..n], wire.as_slice(), "bool/{}", case.name);
        }
    }

    #[test]
    fn null_sentinel_rejected() {
        let fixture = fixture("bool");
        for case in &fixture.null_wire {
            let wire = wire_case(case);
            assert_eq!(bool::decode(&wire).unwrap_err(), ZclError::NullSentinel);
        }
    }

    #[test]
    fn invalid_value_rejected() {
        let fixture = fixture("bool");
        for case in &fixture.invalid_value {
            let wire = wire_case(case);
            assert_eq!(
                bool::decode(&wire).unwrap_err(),
                ZclError::InvalidValue,
                "bool/{}",
                case.name
            );
        }
    }
}

// ---------------------------------------------------------------------------
// ShortText — ROUNDTRIP + NULL_WIRE + INVALID_UTF8
// ---------------------------------------------------------------------------

mod short_text_compliance {
    use super::*;

    #[test]
    fn decode_roundtrip() {
        let fixture = fixture("short_text");
        for case in &fixture.roundtrip {
            let wire = case_wire(case);
            let expected: String = case_value(case);
            let (val, n) = ShortText::decode(&wire)
                .unwrap_or_else(|e| panic!("short_text/{} decode → {e:?}", case.name));
            assert_eq!(val.as_str(), expected, "short_text/{}", case.name);
            assert_eq!(n, wire.len());
        }
    }

    #[test]
    fn encode_roundtrip() {
        let fixture = fixture("short_text");
        let mut buf = [0u8; 256];
        for case in &fixture.roundtrip {
            let wire = case_wire(case);
            let expected: String = case_value(case);
            let s = ShortStr::new(&expected).unwrap();
            let n = ShortText::encode(s, &mut buf)
                .unwrap_or_else(|e| panic!("short_text/{} encode → {e:?}", case.name));
            assert_eq!(&buf[..n], wire.as_slice(), "short_text/{}", case.name);
        }
    }

    #[test]
    fn null_wire_rejected() {
        let fixture = fixture("short_text");
        for case in &fixture.null_wire {
            let wire = wire_case(case);
            assert_eq!(
                ShortText::decode(&wire).unwrap_err(),
                ZclError::NullSentinel
            );
        }
    }

    #[test]
    fn nullable_none_decode() {
        let fixture = fixture("short_text");
        for case in &fixture.null_wire {
            let wire = wire_case(case);
            let (val, n) = Nullable::<ShortText>::decode(&wire).unwrap();
            assert!(val.is_none());
            assert_eq!(n, wire.len());
        }
    }

    #[test]
    fn nullable_none_encode() {
        let fixture = fixture("short_text");
        let mut buf = [0u8; 1];
        for case in &fixture.null_wire {
            let wire = wire_case(case);
            let n = Nullable::<ShortText>::encode(None, &mut buf).unwrap();
            assert_eq!(&buf[..n], wire.as_slice());
        }
    }

    #[test]
    fn invalid_utf8_decode_rejected() {
        let fixture = fixture("short_text");
        for case in &fixture.invalid_utf8 {
            let wire = wire_case(case);
            assert_eq!(
                ShortText::decode(&wire).unwrap_err(),
                ZclError::InvalidUtf8,
                "short_text/{}",
                case.name
            );
        }
    }
}

// ---------------------------------------------------------------------------
// Collection matrix macros
// ---------------------------------------------------------------------------

macro_rules! collection_array_bag_compliance {
    ($mod_name:ident, $coll_schema:ty, $elem_schema:ty, $kind:ty, $fixture:literal) => {
        mod $mod_name {
            use super::*;

            #[test]
            fn decoder_element_values() {
                let fixture = fixture($fixture);
                for case in &fixture.roundtrip {
                    let wire = case_wire(case);
                    let expected_elems = case_values::<$elem_schema>(case);
                    let (coll, n) = <$coll_schema>::decode(&wire).unwrap_or_else(|e| {
                        panic!("{}/{} decode {:?} → {e:?}", $fixture, case.name, wire)
                    });
                    assert_eq!(n, wire.len(), "{}/{}", $fixture, case.name);
                    assert_eq!(
                        coll.len() as usize,
                        expected_elems.len(),
                        "{}/{}",
                        $fixture,
                        case.name
                    );
                    let mut dec = coll.decoder();
                    for (i, &expected) in expected_elems.iter().enumerate() {
                        let val = dec.next().unwrap().unwrap();
                        assert_eq!(val, expected, "{}/{}[{i}]", $fixture, case.name);
                    }
                    assert!(dec.next().is_none());
                    dec.finish().unwrap();
                }
            }

            #[test]
            fn iter_element_values() {
                let fixture = fixture($fixture);
                for case in &fixture.roundtrip {
                    let wire = case_wire(case);
                    let expected_elems = case_values::<$elem_schema>(case);
                    let (coll, _) = <$coll_schema>::decode(&wire).unwrap();
                    let mut i = 0;
                    for result in coll.iter() {
                        let val = result.unwrap();
                        assert_eq!(val, expected_elems[i], "{}/{}[{i}]", $fixture, case.name);
                        i += 1;
                    }
                    assert_eq!(i, expected_elems.len());
                }
            }

            #[test]
            fn encoder_builds_from_scratch() {
                let fixture = fixture($fixture);
                let mut buf = [0u8; 64];
                for case in &fixture.roundtrip {
                    let wire = case_wire(case);
                    let elems = case_values::<$elem_schema>(case);
                    let mut enc = CollectionEncoder::<$kind, $elem_schema>::new(&mut buf)
                        .unwrap_or_else(|e| {
                            panic!("{}/{} encoder new → {e:?}", $fixture, case.name)
                        });
                    for &e in &elems {
                        enc.push(e).unwrap_or_else(|err| {
                            panic!("{}/{} push {e:?} → {err:?}", $fixture, case.name)
                        });
                    }
                    let n = enc
                        .finish()
                        .unwrap_or_else(|e| panic!("{}/{} finish → {e:?}", $fixture, case.name));
                    assert_eq!(&buf[..n], wire.as_slice(), "{}/{}", $fixture, case.name);
                }
            }

            #[test]
            fn null_wire_rejected() {
                let fixture = fixture($fixture);
                for case in &fixture.null_wire {
                    let wire = wire_case(case);
                    assert_eq!(
                        <$coll_schema>::decode(&wire).unwrap_err(),
                        ZclError::NullSentinel,
                        "{}/{}",
                        $fixture,
                        case.name,
                    );
                }
            }

            #[test]
            fn nullable_none_decode() {
                let fixture = fixture($fixture);
                for case in &fixture.null_wire {
                    let wire = wire_case(case);
                    let (val, n) = Nullable::<$coll_schema>::decode(&wire).unwrap();
                    assert!(val.is_none());
                    assert_eq!(n, wire.len());
                }
            }

            #[test]
            fn nullable_none_encode() {
                let fixture = fixture($fixture);
                let mut buf = [0u8; 8];
                for case in &fixture.null_wire {
                    let wire = wire_case(case);
                    let n = Nullable::<$coll_schema>::encode(None, &mut buf).unwrap();
                    assert_eq!(&buf[..n], wire.as_slice());
                }
            }

            #[test]
            fn type_mismatch_rejected() {
                let fixture = fixture($fixture);
                for case in &fixture.type_mismatch {
                    let wire = type_mismatch_wire(case);
                    assert_type_mismatch_case(
                        <$coll_schema>::decode(&wire).unwrap_err(),
                        case,
                        &format!("{}/{}", $fixture, case.name),
                    );
                }
            }

            #[test]
            fn invalid_wire_errors_match_fixture() {
                let fixture = fixture($fixture);
                for case in &fixture.invalid {
                    let wire = invalid_wire(case);
                    let context = format!("{}/{}", $fixture, case.name);
                    assert_zcl_error(<$coll_schema>::decode(&wire).unwrap_err(), case, &context);
                    assert_zcl_error(
                        Nullable::<$coll_schema>::decode(&wire).unwrap_err(),
                        case,
                        &format!("{context} nullable"),
                    );
                }
            }

            #[test]
            fn decoder_finish_rejects_unconsumed_elements() {
                let fixture = fixture($fixture);
                let case = fixture
                    .roundtrip
                    .iter()
                    .find(|case| case.values.len() > 1)
                    .expect("collection fixture should include a multi-element case");
                let wire = case_wire(case);
                let (coll, _) = <$coll_schema>::decode(&wire).unwrap();
                let mut dec = coll.decoder();
                dec.next().unwrap().unwrap();
                assert_eq!(dec.finish().unwrap_err(), ZclError::UnconsumedData);
            }
        }
    };
}

macro_rules! set_compliance {
    ($mod_name:ident, $elem_schema:ty, $policy:ty, $fixture:literal) => {
        mod $mod_name {
            use super::*;

            type Schema = SetOf<$elem_schema, $policy>;

            #[test]
            fn valid_sets_decode_element_values_and_encode() {
                let fixture = fixture($fixture);
                let mut buf = [0u8; 64];
                for case in &fixture.valid {
                    let wire = case_wire(case);
                    let expected_elems = case_values::<$elem_schema>(case);
                    let (coll, n) = Schema::decode(&wire).unwrap_or_else(|e| {
                        panic!("{}/{} decode {:?} → {e:?}", $fixture, case.name, wire)
                    });
                    assert_eq!(n, wire.len());
                    assert_eq!(coll.len() as usize, expected_elems.len());
                    let mut dec = coll.decoder();
                    for (i, &expected) in expected_elems.iter().enumerate() {
                        assert_eq!(
                            dec.next().unwrap().unwrap(),
                            expected,
                            "{}/{}[{i}]",
                            $fixture,
                            case.name
                        );
                    }
                    assert!(dec.next().is_none());
                    dec.finish().unwrap();
                    let written = Schema::encode(coll, &mut buf)
                        .unwrap_or_else(|e| panic!("{}/{} encode → {e:?}", $fixture, case.name));
                    assert_eq!(&buf[..written], wire.as_slice());
                }
            }

            #[test]
            fn encoder_builds_from_scratch() {
                let fixture = fixture($fixture);
                let mut buf = [0u8; 64];
                for case in &fixture.valid {
                    let wire = case_wire(case);
                    let elems = case_values::<$elem_schema>(case);
                    let mut enc =
                        CollectionEncoder::<Set<$policy>, $elem_schema>::new(&mut buf).unwrap();
                    for &e in &elems {
                        enc.push(e).unwrap();
                    }
                    let n = enc.finish().unwrap();
                    assert_eq!(&buf[..n], wire.as_slice(), "{}/{}", $fixture, case.name);
                }
            }

            #[test]
            fn null_wire_rejected() {
                assert_null_wire_rejected::<Schema>($fixture);
            }

            #[test]
            fn nullable_none_decode() {
                assert_nullable_none_decode::<Schema>($fixture);
            }

            #[test]
            fn nullable_none_encode() {
                let mut buf = [0u8; 8];
                assert_nullable_none_encode::<Schema>($fixture, &mut buf);
            }

            #[test]
            fn type_mismatch_rejected() {
                assert_type_mismatch_rejected::<Schema>($fixture);
            }

            #[test]
            fn invalid_wire_errors_match_fixture() {
                assert_invalid_wire_errors_match_fixture::<Schema>($fixture);
                assert_invalid_nullable_errors_match_fixture::<Schema>($fixture);
            }

            #[test]
            fn duplicate_element_rejected() {
                let fixture = fixture($fixture);
                for case in &fixture.duplicate {
                    let wire = wire_case(case);
                    assert_eq!(
                        Schema::decode(&wire).unwrap_err(),
                        ZclError::InvalidValue,
                        "{}/{}",
                        $fixture,
                        case.name
                    );
                }
            }
        }
    };
}

// ---------------------------------------------------------------------------
// Dynamic ZclValueRef parity over the generated fixtures
// ---------------------------------------------------------------------------

mod dynamic_value_compliance {
    use super::*;

    #[test]
    fn decode_encode_roundtrips_generated_vectors() {
        for (fixture_name, fixture) in &FIXTURES.types {
            let type_id = type_id(fixture.type_id);
            for case in dynamic_roundtrip_cases(fixture) {
                let wire = case_wire(case);
                assert_dynamic_value_roundtrip(
                    type_id,
                    &wire,
                    &format!("{fixture_name}/{}", case.name),
                );
            }
        }
    }

    #[test]
    fn nullable_null_wires_roundtrip_when_dynamic_value_can_represent_null() {
        for (fixture_name, fixture) in &FIXTURES.types {
            let type_id = type_id(fixture.type_id);
            if !dynamic_null_supported(type_id) {
                continue;
            }
            for case in &fixture.null_wire {
                let wire = wire_case(case);
                assert_dynamic_value_roundtrip(
                    type_id,
                    &wire,
                    &format!("{fixture_name}/{}", case.name),
                );
            }
        }
    }

    #[test]
    fn scalar_null_sentinels_are_rejected_dynamically() {
        for (fixture_name, fixture) in &FIXTURES.types {
            let type_id = type_id(fixture.type_id);
            if dynamic_null_supported(type_id) {
                continue;
            }
            for case in &fixture.null_wire {
                let wire = wire_case(case);
                assert_eq!(
                    ZclValueRef::decode_with_type(type_id, &wire).unwrap_err(),
                    ZclError::NullSentinel,
                    "{fixture_name}/{}",
                    case.name
                );
            }
        }
    }

    #[test]
    fn reserved_bool_wires_are_rejected_dynamically() {
        let bool_fixture = fixture("bool");
        for case in &bool_fixture.invalid_value {
            let wire = wire_case(case);
            assert_eq!(
                ZclValueRef::decode_with_type(TypeId::Boolean, &wire).unwrap_err(),
                ZclError::InvalidValue,
                "bool/{}",
                case.name
            );
        }
    }

    #[test]
    fn dynamic_text_preserves_non_utf8_wires() {
        let text_fixture = fixture("short_text");
        for case in &text_fixture.invalid_utf8 {
            let wire = wire_case(case);
            assert_dynamic_value_roundtrip(
                TypeId::CharacterString,
                &wire,
                &format!("short_text/{}", case.name),
            );
        }
    }
}

// ---------------------------------------------------------------------------
// Array matrix
// ---------------------------------------------------------------------------

collection_array_bag_compliance!(
    coll_array_u8_compliance,
    ArrayOf<u8>,
    u8,
    Array,
    "coll_array_u8"
);
collection_array_bag_compliance!(
    coll_array_u16_compliance,
    ArrayOf<u16>,
    u16,
    Array,
    "coll_array_u16"
);
collection_array_bag_compliance!(
    coll_array_i16_compliance,
    ArrayOf<i16>,
    i16,
    Array,
    "coll_array_i16"
);
collection_array_bag_compliance!(
    coll_array_bool_compliance,
    ArrayOf<bool>,
    bool,
    Array,
    "coll_array_bool"
);

// ---------------------------------------------------------------------------
// Bag matrix
// ---------------------------------------------------------------------------

collection_array_bag_compliance!(coll_bag_u8_compliance, BagOf<u8>, u8, Bag, "coll_bag_u8");
collection_array_bag_compliance!(
    coll_bag_u16_compliance,
    BagOf<u16>,
    u16,
    Bag,
    "coll_bag_u16"
);

// ---------------------------------------------------------------------------
// Set matrix — RawUniqueSet policy, element values verified
// ---------------------------------------------------------------------------

set_compliance!(coll_set_u8_compliance, u8, RawUniqueSet, "coll_set_u8");
set_compliance!(coll_set_u16_compliance, u16, RawUniqueSet, "coll_set_u16");

// ---------------------------------------------------------------------------
// Struct — (u8, u16) pair via StructEncoder / StructDecoder / StructOf
// ---------------------------------------------------------------------------

struct PairStruct;

impl ZclStructSchema for PairStruct {
    type Value<'a> = (u8, u16);

    fn decode_fields<'a>(dec: &mut StructDecoder<'a>) -> Result<(u8, u16), ZclError> {
        Ok((dec.field::<u8>()?, dec.field::<u16>()?))
    }

    fn encode_fields(value: (u8, u16), enc: &mut StructEncoder<'_>) -> Result<(), ZclError> {
        enc.field::<u8>(value.0)?;
        enc.field::<u16>(value.1)
    }
}

// ---------------------------------------------------------------------------
// Nesting — ArrayOf<ArrayOf<u8>>
// ---------------------------------------------------------------------------

mod coll_array_of_array_u8_compliance {
    use super::*;

    type OuterSchema = ArrayOf<ArrayOf<u8>>;

    #[test]
    fn decode_outer_count_and_inner_elements() {
        let fixture = fixture("coll_nested_array_u8");
        for case in &fixture.roundtrip {
            let outer_wire = case_wire(case);
            let inner_wires = case
                .inner_wires
                .iter()
                .map(|wire| parse_wire(wire))
                .collect::<Vec<_>>();
            let (outer, n) = OuterSchema::decode(&outer_wire)
                .unwrap_or_else(|e| panic!("coll_nested_array_u8/{} decode → {e:?}", case.name));
            assert_eq!(n, outer_wire.len());
            assert_eq!(outer.len() as usize, inner_wires.len());
            let mut dec = outer.decoder();
            for (i, inner_wire) in inner_wires.iter().enumerate() {
                let inner = dec.next().unwrap().unwrap();
                let mut buf = [0u8; 32];
                let m = ArrayOf::<u8>::encode(inner, &mut buf).unwrap();
                assert_eq!(
                    &buf[..m],
                    inner_wire.as_slice(),
                    "coll_nested_array_u8/{}[{i}]",
                    case.name
                );
            }
            assert!(dec.next().is_none());
            dec.finish().unwrap();
        }
    }

    #[test]
    fn encoder_builds_from_scratch() {
        let fixture = fixture("coll_nested_array_u8");
        let mut buf = [0u8; 128];
        for case in &fixture.roundtrip {
            let wire = case_wire(case);
            let inner_wires = case
                .inner_wires
                .iter()
                .map(|wire| parse_wire(wire))
                .collect::<Vec<_>>();
            let mut enc = CollectionEncoder::<Array, ArrayOf<u8>>::new(&mut buf).unwrap();
            for inner_wire in &inner_wires {
                let (inner, _) = ArrayOf::<u8>::decode(inner_wire).unwrap();
                enc.push(inner).unwrap();
            }
            let n = enc.finish().unwrap();
            assert_eq!(
                &buf[..n],
                wire.as_slice(),
                "coll_nested_array_u8/{}",
                case.name
            );
        }
    }

    #[test]
    fn null_wire_rejected() {
        let fixture = fixture("coll_nested_array_u8");
        for case in &fixture.null_wire {
            let wire = wire_case(case);
            assert_eq!(
                OuterSchema::decode(&wire).unwrap_err(),
                ZclError::NullSentinel
            );
        }
    }

    #[test]
    fn nullable_none_decode() {
        let fixture = fixture("coll_nested_array_u8");
        for case in &fixture.null_wire {
            let wire = wire_case(case);
            let (val, n) = Nullable::<OuterSchema>::decode(&wire).unwrap();
            assert!(val.is_none());
            assert_eq!(n, wire.len());
        }
    }

    #[test]
    fn nullable_none_encode() {
        let fixture = fixture("coll_nested_array_u8");
        let mut buf = [0u8; 4];
        for case in &fixture.null_wire {
            let wire = wire_case(case);
            let n = Nullable::<OuterSchema>::encode(None, &mut buf).unwrap();
            assert_eq!(&buf[..n], wire.as_slice());
        }
    }

    #[test]
    fn type_mismatch_rejected() {
        let fixture = fixture("coll_nested_array_u8");
        for case in &fixture.type_mismatch {
            let wire = type_mismatch_wire(case);
            assert_type_mismatch_case(
                OuterSchema::decode(&wire).unwrap_err(),
                case,
                &format!("coll_nested_array_u8/{}", case.name),
            );
        }
    }

    #[test]
    fn invalid_wire_errors_match_fixture() {
        let fixture = fixture("coll_nested_array_u8");
        for case in &fixture.invalid {
            let wire = invalid_wire(case);
            let context = format!("coll_nested_array_u8/{}", case.name);
            assert_zcl_error(OuterSchema::decode(&wire).unwrap_err(), case, &context);
        }
    }

    #[test]
    fn decoder_finish_rejects_unconsumed_elements() {
        let fixture = fixture("coll_nested_array_u8");
        let case = fixture
            .roundtrip
            .iter()
            .find(|case| case.inner_wires.len() > 1)
            .expect("nested array fixture should include multiple inner arrays");
        let wire = case_wire(case);
        let (outer, _) = OuterSchema::decode(&wire).unwrap();
        let mut dec = outer.decoder();
        dec.next().unwrap().unwrap();
        assert_eq!(dec.finish().unwrap_err(), ZclError::UnconsumedData);
    }
}

// ---------------------------------------------------------------------------
// Nesting — ArrayOf<StructOf<PairStruct>>
// ---------------------------------------------------------------------------

mod coll_array_of_struct_pair_compliance {
    use super::*;

    type OuterSchema = ArrayOf<StructOf<PairStruct>>;

    #[test]
    fn decode_element_values() {
        let fixture = fixture("coll_array_of_struct_pair");
        for case in &fixture.roundtrip {
            let wire = case_wire(case);
            let expected_pairs = case_pairs(case);
            let (outer, n) = OuterSchema::decode(&wire).unwrap_or_else(|e| {
                panic!("coll_array_of_struct_pair/{} decode → {e:?}", case.name)
            });
            assert_eq!(n, wire.len());
            assert_eq!(outer.len() as usize, expected_pairs.len());
            let mut dec = outer.decoder();
            for (i, &expected) in expected_pairs.iter().enumerate() {
                let val = dec.next().unwrap().unwrap();
                assert_eq!(
                    val, expected,
                    "coll_array_of_struct_pair/{}[{i}]",
                    case.name
                );
            }
            assert!(dec.next().is_none());
            dec.finish().unwrap();
        }
    }

    #[test]
    fn encoder_builds_from_scratch() {
        let fixture = fixture("coll_array_of_struct_pair");
        let mut buf = [0u8; 128];
        for case in &fixture.roundtrip {
            let wire = case_wire(case);
            let pairs = case_pairs(case);
            let mut enc = CollectionEncoder::<Array, StructOf<PairStruct>>::new(&mut buf).unwrap();
            for &pair in &pairs {
                enc.push(pair).unwrap();
            }
            let n = enc.finish().unwrap();
            assert_eq!(
                &buf[..n],
                wire.as_slice(),
                "coll_array_of_struct_pair/{}",
                case.name
            );
        }
    }

    #[test]
    fn null_wire_rejected() {
        let fixture = fixture("coll_array_of_struct_pair");
        for case in &fixture.null_wire {
            let wire = wire_case(case);
            assert_eq!(
                OuterSchema::decode(&wire).unwrap_err(),
                ZclError::NullSentinel
            );
        }
    }

    #[test]
    fn nullable_none_decode() {
        let fixture = fixture("coll_array_of_struct_pair");
        for case in &fixture.null_wire {
            let wire = wire_case(case);
            let (val, n) = Nullable::<OuterSchema>::decode(&wire).unwrap();
            assert!(val.is_none());
            assert_eq!(n, wire.len());
        }
    }

    #[test]
    fn nullable_none_encode() {
        let fixture = fixture("coll_array_of_struct_pair");
        let mut buf = [0u8; 4];
        for case in &fixture.null_wire {
            let wire = wire_case(case);
            let n = Nullable::<OuterSchema>::encode(None, &mut buf).unwrap();
            assert_eq!(&buf[..n], wire.as_slice());
        }
    }

    #[test]
    fn type_mismatch_rejected() {
        let fixture = fixture("coll_array_of_struct_pair");
        for case in &fixture.type_mismatch {
            let wire = type_mismatch_wire(case);
            assert_type_mismatch_case(
                OuterSchema::decode(&wire).unwrap_err(),
                case,
                &format!("coll_array_of_struct_pair/{}", case.name),
            );
        }
    }

    #[test]
    fn invalid_wire_errors_match_fixture() {
        let fixture = fixture("coll_array_of_struct_pair");
        for case in &fixture.invalid {
            let wire = invalid_wire(case);
            let context = format!("coll_array_of_struct_pair/{}", case.name);
            assert_zcl_error(OuterSchema::decode(&wire).unwrap_err(), case, &context);
        }
    }

    #[test]
    fn decoder_finish_rejects_unconsumed_elements() {
        let fixture = fixture("coll_array_of_struct_pair");
        let case = fixture
            .roundtrip
            .iter()
            .find(|case| case.values.len() > 1)
            .expect("array-of-struct fixture should include multiple elements");
        let wire = case_wire(case);
        let (outer, _) = OuterSchema::decode(&wire).unwrap();
        let mut dec = outer.decoder();
        dec.next().unwrap().unwrap();
        assert_eq!(dec.finish().unwrap_err(), ZclError::UnconsumedData);
    }
}

// ---------------------------------------------------------------------------
// Nesting — struct containing an ArrayOf<u8> field
// ---------------------------------------------------------------------------

struct ArrayFieldStruct;

impl ZclStructSchema for ArrayFieldStruct {
    type Value<'a> = (u8, ArrayRef<'a, u8>);

    fn decode_fields<'a>(dec: &mut StructDecoder<'a>) -> Result<Self::Value<'a>, ZclError> {
        Ok((dec.field::<u8>()?, dec.field::<ArrayOf<u8>>()?))
    }

    fn encode_fields(value: Self::Value<'_>, enc: &mut StructEncoder<'_>) -> Result<(), ZclError> {
        enc.field::<u8>(value.0)?;
        enc.field::<ArrayOf<u8>>(value.1)
    }
}

mod coll_struct_with_array_compliance {
    use super::*;

    #[test]
    fn decode_field_values() {
        let fixture = fixture("coll_struct_with_array");
        for case in &fixture.roundtrip {
            let wire = case_wire(case);
            let (expected_u8, expected_arr) = case_struct_with_array(case);
            let ((u8_val, arr_ref), n) = StructOf::<ArrayFieldStruct>::decode(&wire)
                .unwrap_or_else(|e| panic!("coll_struct_with_array/{} decode → {e:?}", case.name));
            assert_eq!(n, wire.len());
            assert_eq!(u8_val, expected_u8);
            assert_eq!(arr_ref.len() as usize, expected_arr.len());
            let mut dec = arr_ref.decoder();
            for (i, &expected_elem) in expected_arr.iter().enumerate() {
                assert_eq!(
                    dec.next().unwrap().unwrap(),
                    expected_elem,
                    "coll_struct_with_array/{}[{i}]",
                    case.name
                );
            }
            assert!(dec.next().is_none());
            dec.finish().unwrap();
        }
    }

    #[test]
    fn schema_encode_roundtrip() {
        let fixture = fixture("coll_struct_with_array");
        let mut buf = [0u8; 32];
        for case in &fixture.roundtrip {
            let wire = case_wire(case);
            let (val, _) = StructOf::<ArrayFieldStruct>::decode(&wire).unwrap();
            let n = StructOf::<ArrayFieldStruct>::encode(val, &mut buf).unwrap();
            assert_eq!(
                &buf[..n],
                wire.as_slice(),
                "coll_struct_with_array/{}",
                case.name
            );
        }
    }

    #[test]
    fn encoder_builds_from_scratch() {
        let fixture = fixture("coll_struct_with_array");
        let mut buf = [0u8; 32];
        let mut arr_scratch = [0u8; 16];
        for case in &fixture.roundtrip {
            let wire = case_wire(case);
            let (u8_val, arr_elems) = case_struct_with_array(case);
            let mut enc = StructEncoder::new(&mut buf).unwrap();
            enc.field::<u8>(u8_val).unwrap();
            let mut arr_enc = CollectionEncoder::<Array, u8>::new(&mut arr_scratch).unwrap();
            for &e in &arr_elems {
                arr_enc.push(e).unwrap();
            }
            let arr_n = arr_enc.finish().unwrap();
            let (arr_ref, _) = ArrayOf::<u8>::decode(&arr_scratch[..arr_n]).unwrap();
            enc.field::<ArrayOf<u8>>(arr_ref).unwrap();
            let n = enc.finish().unwrap();
            assert_eq!(
                &buf[..n],
                wire.as_slice(),
                "coll_struct_with_array/{}",
                case.name
            );
        }
    }

    #[test]
    fn null_wire_rejected() {
        let fixture = fixture("coll_struct_with_array");
        for case in &fixture.null_wire {
            let wire = wire_case(case);
            assert_eq!(
                StructOf::<ArrayFieldStruct>::decode(&wire).unwrap_err(),
                ZclError::NullSentinel
            );
        }
    }

    #[test]
    fn nullable_none_decode() {
        let fixture = fixture("coll_struct_with_array");
        for case in &fixture.null_wire {
            let wire = wire_case(case);
            let (val, n) = Nullable::<StructOf<ArrayFieldStruct>>::decode(&wire).unwrap();
            assert!(val.is_none());
            assert_eq!(n, wire.len());
        }
    }

    #[test]
    fn nullable_none_encode() {
        let fixture = fixture("coll_struct_with_array");
        let mut buf = [0u8; 4];
        for case in &fixture.null_wire {
            let wire = wire_case(case);
            let n = Nullable::<StructOf<ArrayFieldStruct>>::encode(None, &mut buf).unwrap();
            assert_eq!(&buf[..n], wire.as_slice());
        }
    }

    #[test]
    fn invalid_wire_errors_match_fixture() {
        let fixture = fixture("coll_struct_with_array");
        for case in &fixture.invalid {
            let wire = invalid_wire(case);
            let context = format!("coll_struct_with_array/{}", case.name);
            assert_zcl_error(
                StructOf::<ArrayFieldStruct>::decode(&wire).unwrap_err(),
                case,
                &context,
            );
        }
    }
}

// ---------------------------------------------------------------------------
// Struct — (u8, u16) pair via StructEncoder / StructDecoder / StructOf
// ---------------------------------------------------------------------------

mod struct_pair_compliance {
    use super::*;

    #[test]
    fn schema_decode_roundtrip() {
        let fixture = fixture("coll_struct_pair");
        for case in &fixture.roundtrip {
            let wire = case_wire(case);
            let expected = case_pair(case);
            let (val, n) = StructOf::<PairStruct>::decode(&wire)
                .unwrap_or_else(|e| panic!("coll_struct_pair/{} decode → {e:?}", case.name));
            assert_eq!(val, expected, "coll_struct_pair/{}", case.name);
            assert_eq!(n, wire.len());
        }
    }

    #[test]
    fn schema_encode_roundtrip() {
        let fixture = fixture("coll_struct_pair");
        let mut buf = [0u8; 16];
        for case in &fixture.roundtrip {
            let wire = case_wire(case);
            let expected = case_pair(case);
            let n = StructOf::<PairStruct>::encode(expected, &mut buf).unwrap_or_else(|e| {
                panic!("coll_struct_pair/{} encode {expected:?} → {e:?}", case.name)
            });
            assert_eq!(&buf[..n], wire.as_slice(), "coll_struct_pair/{}", case.name);
        }
    }

    #[test]
    fn encoder_builds_from_scratch() {
        let fixture = fixture("coll_struct_pair");
        let mut buf = [0u8; 16];
        for case in &fixture.roundtrip {
            let wire = case_wire(case);
            let (u8_val, u16_val) = case_pair(case);
            let mut enc = StructEncoder::new(&mut buf).unwrap();
            enc.field::<u8>(u8_val).unwrap();
            enc.field::<u16>(u16_val).unwrap();
            let n = enc.finish().unwrap();
            assert_eq!(&buf[..n], wire.as_slice(), "coll_struct_pair/{}", case.name);
        }
    }

    #[test]
    fn decoder_streams_fields() {
        let fixture = fixture("coll_struct_pair");
        for case in &fixture.roundtrip {
            let wire = case_wire(case);
            let (expected_u8, expected_u16) = case_pair(case);
            let (mut dec, _) = StructDecoder::new(&wire).unwrap_or_else(|e| {
                panic!("coll_struct_pair/{} StructDecoder::new → {e:?}", case.name)
            });
            let v1 = dec.field::<u8>().unwrap();
            let v2 = dec.field::<u16>().unwrap();
            dec.finish().unwrap();
            assert_eq!(v1, expected_u8, "coll_struct_pair/{}", case.name);
            assert_eq!(v2, expected_u16, "coll_struct_pair/{}", case.name);
        }
    }

    #[test]
    fn decoder_finish_rejects_unconsumed_fields() {
        let fixture = fixture("coll_struct_pair");
        let case = fixture
            .roundtrip
            .first()
            .expect("struct pair fixture should include a roundtrip case");
        let wire = case_wire(case);
        let (mut dec, _) = StructDecoder::new(&wire).unwrap();
        let _: u8 = dec.field::<u8>().unwrap();
        assert_eq!(dec.finish().unwrap_err(), ZclError::UnconsumedData);
    }

    #[test]
    fn null_wire_rejected() {
        let fixture = fixture("coll_struct_pair");
        for case in &fixture.null_wire {
            let wire = wire_case(case);
            assert_eq!(
                StructOf::<PairStruct>::decode(&wire).unwrap_err(),
                ZclError::NullSentinel
            );
        }
    }

    #[test]
    fn nullable_none_decode() {
        let fixture = fixture("coll_struct_pair");
        for case in &fixture.null_wire {
            let wire = wire_case(case);
            let (val, n) = Nullable::<StructOf<PairStruct>>::decode(&wire).unwrap();
            assert!(val.is_none());
            assert_eq!(n, wire.len());
        }
    }

    #[test]
    fn nullable_none_encode() {
        let fixture = fixture("coll_struct_pair");
        let mut buf = [0u8; 4];
        for case in &fixture.null_wire {
            let wire = wire_case(case);
            let n = Nullable::<StructOf<PairStruct>>::encode(None, &mut buf).unwrap();
            assert_eq!(&buf[..n], wire.as_slice());
        }
    }

    #[test]
    fn invalid_wire_errors_match_fixture() {
        let fixture = fixture("coll_struct_pair");
        for case in &fixture.invalid {
            let wire = invalid_wire(case);
            let context = format!("coll_struct_pair/{}", case.name);
            assert_zcl_error(
                StructOf::<PairStruct>::decode(&wire).unwrap_err(),
                case,
                &context,
            );
        }
    }
}
