name: Examples

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      examples: ${{ steps.list.outputs.examples }}
    steps:
      - uses: actions/checkout@v4

      - id: list
        run: |
          examples=$(find examples -mindepth 1 -maxdepth 1 -type d | xargs -I{} basename {} | sort | jq -R . | jq -sc .)
          echo "examples=$examples" >> "$GITHUB_OUTPUT"

  build:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: ${{ fromJson(needs.discover.outputs.examples) }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        working-directory: ./examples/${{ matrix.example }}
        run: rustup show

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            examples/${{ matrix.example }}/target
          key: ${{ runner.os }}-${{ matrix.example }}-${{ hashFiles(format('examples/{0}/Cargo.lock', matrix.example), format('examples/{0}/rust-toolchain.toml', matrix.example)) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.example }}-

      - name: Build ${{ matrix.example }}
        working-directory: ./examples/${{ matrix.example }}
        env:
          CARGO_INCREMENTAL: 0
        run: cargo build
